packages:
  - packages/*
  - l1
  - aztec
  - examples

ignoredBuiltDependencies:
  - bcrypto
  - bigint-buffer
  - esbuild
  - leveldown
  - lmdb
  - msgpackr-extract
  - protobufjs
  - unrs-resolver

linkWorkspacePackages: true

onlyBuiltDependencies:
  - c-kzg

overrides:
  '@aztec/aztec.js': 2.0.3
  '@aztec/circuit-types': 2.0.3
  '@aztec/circuits.js': 2.0.3
  '@aztec/cli': 2.0.3
  '@aztec/constants': 2.0.3
  '@aztec/foundation': 2.0.3
  '@aztec/noir-contracts.js': 2.0.3
  '@aztec/protocol-contracts': 2.0.3
  '@aztec/stdlib': 2.0.3
  '@aztec/types': 2.0.3
  glob: ^11.0.0

preferWorkspacePackages: true
