
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type UnencryptedL2Log,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import BeaconContractArtifactJson from './beacon-Beacon.json' assert { type: 'json' };
export const BeaconContractArtifact = loadContractArtifact(BeaconContractArtifactJson as NoirCompiledContract);


      export type TargetOverrideChangeScheduled = {
        source: AztecAddressLike
old_target: AztecAddressLike
new_target: AztecAddressLike
effective_block: FieldLike
      }
    

      export type TargetChangeScheduled = {
        old_target: AztecAddressLike
new_target: AztecAddressLike
effective_block: FieldLike
      }
    

      export type AdminChanged = {
        old_admin: AztecAddressLike
new_admin: AztecAddressLike
      }
    

/**
 * Type-safe interface for contract Beacon;
 */
export class BeaconContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, BeaconContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, BeaconContract.artifact, wallet) as Promise<BeaconContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, target: AztecAddressLike) {
    return new DeployMethod<BeaconContract>(PublicKeys.default(), wallet, BeaconContractArtifact, BeaconContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, target: AztecAddressLike) {
    return new DeployMethod<BeaconContract>(publicKeys, wallet, BeaconContractArtifact, BeaconContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BeaconContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BeaconContract['methods'][M]>
  ) {
    return new DeployMethod<BeaconContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BeaconContractArtifact,
      BeaconContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BeaconContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'target' | 'overrides' | 'admin'> {
      return {
        target: {
      slot: new Fr(1n),
    },
overrides: {
      slot: new Fr(2n),
    },
admin: {
      slot: new Fr(3n),
    }
      } as ContractStorageLayout<'target' | 'overrides' | 'admin'>;
    }
    

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, packed_note_content: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, packed_note_content: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin_public() */
    get_admin_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin_unconstrained() */
    get_admin_unconstrained: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_default_target_unconstrained() */
    get_default_target_unconstrained: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_target_private(source: struct) */
    get_target_private: ((source: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_target_public(source: struct) */
    get_target_public: ((source: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_target_unconstrained(source: struct) */
    get_target_unconstrained: ((source: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(admin: struct, target: struct) */
    init: ((admin: AztecAddressLike, target: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_log(log_plaintext: struct, tx_hash: field, unique_note_hashes_in_tx: struct, first_nullifier_in_tx: field, recipient: struct) */
    process_log: ((log_plaintext: { storage: FieldLike[], len: (bigint | number) }, tx_hash: FieldLike, unique_note_hashes_in_tx: { storage: FieldLike[], len: (bigint | number) }, first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_admin(from: struct, new_admin: struct, nonce: field) */
    set_admin: ((from: AztecAddressLike, new_admin: AztecAddressLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_target(from: struct, new_target: struct, nonce: field) */
    set_target: ((from: AztecAddressLike, new_target: AztecAddressLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_target_override(from: struct, source: struct, target: struct, nonce: field) */
    set_target_override: ((from: AztecAddressLike, source: AztecAddressLike, target: AztecAddressLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { TargetOverrideChangeScheduled: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, TargetChangeScheduled: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, AdminChanged: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      TargetOverrideChangeScheduled: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "source",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "old_target",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "new_target",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "effective_block",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Beacon::TargetOverrideChangeScheduled"
},
        eventSelector: EventSelector.fromString("0xcdff605f"),
        fieldNames: ["source","old_target","new_target","effective_block"],
      },
TargetChangeScheduled: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "old_target",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "new_target",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "effective_block",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Beacon::TargetChangeScheduled"
},
        eventSelector: EventSelector.fromString("0xec58b72d"),
        fieldNames: ["old_target","new_target","effective_block"],
      },
AdminChanged: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "old_admin",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "new_admin",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "Beacon::AdminChanged"
},
        eventSelector: EventSelector.fromString("0x96eff39a"),
        fieldNames: ["old_admin","new_admin"],
      }
    };
  }
  
}
