
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import PortalContractArtifactJson from './portal-Portal.json' with { type: 'json' };
export const PortalContractArtifact = loadContractArtifact(PortalContractArtifactJson as NoirCompiledContract);


      export type Withdraw = {
        token: EthAddressLike
from: AztecAddressLike
to: EthAddressLike
amount: (bigint | number)
      }
    

      export type Register = {
        eth_token: EthAddressLike
aztec_token: AztecAddressLike
      }
    

      export type Deposit = {
        eth_token: EthAddressLike
recipient: AztecAddressLike
amount: (bigint | number)
message_leaf_index: FieldLike
      }
    

/**
 * Type-safe interface for contract Portal;
 */
export class PortalContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, PortalContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, PortalContract.artifact, wallet) as Promise<PortalContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, l1_portal: EthAddressLike, token_contract_class_id: WrappedFieldLike, shield_gateway: AztecAddressLike) {
    return new DeployMethod<PortalContract>(PublicKeys.default(), wallet, PortalContractArtifact, PortalContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, l1_portal: EthAddressLike, token_contract_class_id: WrappedFieldLike, shield_gateway: AztecAddressLike) {
    return new DeployMethod<PortalContract>(publicKeys, wallet, PortalContractArtifact, PortalContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PortalContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PortalContract['methods'][M]>
  ) {
    return new DeployMethod<PortalContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PortalContractArtifact,
      PortalContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PortalContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PortalContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'l1_tokens' | 'l2_tokens'> {
      return {
        config: {
      slot: new Fr(1n),
    },
l1_tokens: {
      slot: new Fr(5n),
    },
l2_tokens: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'config' | 'l1_tokens' | 'l2_tokens'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** claim_public(eth_token: struct, recipient: struct, amount: integer, message_leaf_index: field) */
    claim_public: ((eth_token: EthAddressLike, recipient: AztecAddressLike, amount: (bigint | number), message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_shielded(eth_token: struct, recipient: struct, amount: integer, message_leaf_index: field) */
    claim_shielded: ((eth_token: EthAddressLike, recipient: AztecAddressLike, amount: (bigint | number), message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(l1_portal: struct, token_contract_class_id: struct, shield_gateway: struct) */
    constructor: ((l1_portal: EthAddressLike, token_contract_class_id: WrappedFieldLike, shield_gateway: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config_private() */
    get_config_private: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config_public() */
    get_config_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_l1_token_unconstrained(aztec_token: struct) */
    get_l1_token_unconstrained: ((aztec_token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_l2_token_unconstrained(eth_token: struct) */
    get_l2_token_unconstrained: ((eth_token: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_registered_l1_unconstrained(eth_token: struct) */
    is_registered_l1_unconstrained: ((eth_token: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_registered_l2_unconstrained(aztec_token: struct) */
    is_registered_l2_unconstrained: ((aztec_token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_private(eth_token: struct, aztec_token: struct, name: string, name_len: integer, symbol: string, symbol_len: integer, decimals: integer, message_leaf_index: field) */
    register_private: ((eth_token: EthAddressLike, aztec_token: AztecAddressLike, name: string, name_len: (bigint | number), symbol: string, symbol_len: (bigint | number), decimals: (bigint | number), message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_public(eth_token: struct, from: struct, recipient: struct, amount: integer, withdrawNonce: field, burnNonce: field) */
    withdraw_public: ((eth_token: EthAddressLike, from: AztecAddressLike, recipient: EthAddressLike, amount: (bigint | number), withdrawNonce: FieldLike, burnNonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Withdraw: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, Register: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, Deposit: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Withdraw: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::eth_address::EthAddress"
            }
        },
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::eth_address::EthAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        }
    ],
    "path": "Portal::Withdraw"
},
        eventSelector: EventSelector.fromString("0x3896c256"),
        fieldNames: ["token","from","to","amount"],
      },
Register: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "eth_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::eth_address::EthAddress"
            }
        },
        {
            "name": "aztec_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "Portal::Register"
},
        eventSelector: EventSelector.fromString("0xd3cd3138"),
        fieldNames: ["eth_token","aztec_token"],
      },
Deposit: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "eth_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::eth_address::EthAddress"
            }
        },
        {
            "name": "recipient",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "message_leaf_index",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Portal::Deposit"
},
        eventSelector: EventSelector.fromString("0x2310ce0f"),
        fieldNames: ["eth_token","recipient","amount","message_leaf_index"],
      }
    };
  }
  
}
