
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type UnencryptedL2Log,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import ShieldGatewayStorageContractArtifactJson from './shield_gateway_storage-ShieldGatewayStorage.json' assert { type: 'json' };
export const ShieldGatewayStorageContractArtifact = loadContractArtifact(ShieldGatewayStorageContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ShieldGatewayStorage;
 */
export class ShieldGatewayStorageContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, ShieldGatewayStorageContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, ShieldGatewayStorageContract.artifact, wallet) as Promise<ShieldGatewayStorageContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<ShieldGatewayStorageContract>(PublicKeys.default(), wallet, ShieldGatewayStorageContractArtifact, ShieldGatewayStorageContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<ShieldGatewayStorageContract>(publicKeys, wallet, ShieldGatewayStorageContractArtifact, ShieldGatewayStorageContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ShieldGatewayStorageContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<ShieldGatewayStorageContract['methods'][M]>
  ) {
    return new DeployMethod<ShieldGatewayStorageContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      ShieldGatewayStorageContractArtifact,
      ShieldGatewayStorageContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ShieldGatewayStorageContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'authorized_caller' | 'channel_balances' | 'channel_thresholds'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
authorized_caller: {
      slot: new Fr(2n),
    },
channel_balances: {
      slot: new Fr(3n),
    },
channel_thresholds: {
      slot: new Fr(4n),
    }
      } as ContractStorageLayout<'admin' | 'authorized_caller' | 'channel_balances' | 'channel_thresholds'>;
    }
    

  public static get notes(): ContractNotes<'U253Note'> {
    return {
      U253Note: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'U253Note'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, packed_note_content: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, packed_note_content: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin_unconstrained() */
    get_admin_unconstrained: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_authorized_caller_unconstrained() */
    get_authorized_caller_unconstrained: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_channel_balance(key: field) */
    get_channel_balance: ((key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_channel_threshold(key: struct) */
    get_channel_threshold: ((key: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_channel_threshold_private(key: struct) */
    get_channel_threshold_private: ((key: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(admin: struct) */
    init: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_channel_balance(key: field, value: struct, owner: struct) */
    initialize_channel_balance: ((key: FieldLike, value: { value: FieldLike }, owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_channel_initialized(key: field) */
    is_channel_initialized: ((key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_channel_initialized_unconstrained(key: field) */
    is_channel_initialized_unconstrained: ((key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_log(log_plaintext: struct, tx_hash: field, unique_note_hashes_in_tx: struct, first_nullifier_in_tx: field, recipient: struct) */
    process_log: ((log_plaintext: { storage: FieldLike[], len: (bigint | number) }, tx_hash: FieldLike, unique_note_hashes_in_tx: { storage: FieldLike[], len: (bigint | number) }, first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_authorized_caller(caller: struct) */
    set_authorized_caller: ((caller: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_channel_balance(key: field, value: struct, owner: struct) */
    set_channel_balance: ((key: FieldLike, value: { value: FieldLike }, owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_channel_threshold(key: struct, value: struct) */
    set_channel_threshold: ((key: AztecAddressLike, value: { value: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
