
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type UnencryptedL2Log,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import TokenContractArtifactJson from './token-Token.json' assert { type: 'json' };
export const TokenContractArtifact = loadContractArtifact(TokenContractArtifactJson as NoirCompiledContract);


      export type Unshield = {
        from: AztecAddressLike
amount: FieldLike
      }
    

      export type Transfer = {
        from: AztecAddressLike
to: AztecAddressLike
amount: FieldLike
      }
    

      export type Shield = {
        from: AztecAddressLike
amount: FieldLike
      }
    

      export type Mint = {
        to: AztecAddressLike
amount: FieldLike
      }
    

      export type Burn = {
        from: AztecAddressLike
amount: FieldLike
      }
    

/**
 * Type-safe interface for contract Token;
 */
export class TokenContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, TokenContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, TokenContract.artifact, wallet) as Promise<TokenContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, minter: AztecAddressLike, name: string, symbol: string, decimals: (bigint | number)) {
    return new DeployMethod<TokenContract>(PublicKeys.default(), wallet, TokenContractArtifact, TokenContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, minter: AztecAddressLike, name: string, symbol: string, decimals: (bigint | number)) {
    return new DeployMethod<TokenContract>(publicKeys, wallet, TokenContractArtifact, TokenContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TokenContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TokenContract['methods'][M]>
  ) {
    return new DeployMethod<TokenContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TokenContractArtifact,
      TokenContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TokenContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'minter' | 'shield_gateway_beacon' | 'private_balances' | 'public_balances' | 'total_supply' | 'shielded_supply' | 'name' | 'symbol' | 'decimals'> {
      return {
        minter: {
      slot: new Fr(1n),
    },
shield_gateway_beacon: {
      slot: new Fr(3n),
    },
private_balances: {
      slot: new Fr(5n),
    },
public_balances: {
      slot: new Fr(6n),
    },
total_supply: {
      slot: new Fr(7n),
    },
shielded_supply: {
      slot: new Fr(8n),
    },
name: {
      slot: new Fr(9n),
    },
symbol: {
      slot: new Fr(11n),
    },
decimals: {
      slot: new Fr(13n),
    }
      } as ContractStorageLayout<'minter' | 'shield_gateway_beacon' | 'private_balances' | 'public_balances' | 'total_supply' | 'shielded_supply' | 'name' | 'symbol' | 'decimals'>;
    }
    

  public static get notes(): ContractNotes<'U253Note'> {
    return {
      U253Note: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'U253Note'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** balance_of_private(owner: struct) */
    balance_of_private: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** balance_of_public(owner: struct) */
    balance_of_public: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_private(from: struct, amount: field, nonce: field) */
    burn_private: ((from: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_public(from: struct, amount: field, nonce: field) */
    burn_public: ((from: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_authwit(inner_hash: field) */
    cancel_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, packed_note_content: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, packed_note_content: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_mint_shielded(to: struct, amount: field, hiding_point_slot: field) */
    finalize_mint_shielded: ((to: AztecAddressLike, amount: FieldLike, hiding_point_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_transfer_public_to_private(amount: field, hiding_point_slot: field) */
    finalize_transfer_public_to_private: ((amount: FieldLike, hiding_point_slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_shield_gateway_beacon_private() */
    get_shield_gateway_beacon_private: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_shield_gateway_beacon_public() */
    get_shield_gateway_beacon_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_shield_gateway_beacon_unconstrained() */
    get_shield_gateway_beacon_unconstrained: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_shield_gateway_private() */
    get_shield_gateway_private: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_shield_gateway_public() */
    get_shield_gateway_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(minter: struct, name: string, symbol: string, decimals: integer) */
    init: ((minter: AztecAddressLike, name: string, symbol: string, decimals: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_public(to: struct, amount: field) */
    mint_public: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_shielded(to: struct, amount: field) */
    mint_shielded: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** prepare_private_balance_increase(to: struct, from: struct) */
    prepare_private_balance_increase: ((to: AztecAddressLike, from: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_decimals() */
    private_get_decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_name() */
    private_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_get_symbol() */
    private_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_log(log_plaintext: struct, tx_hash: field, unique_note_hashes_in_tx: struct, first_nullifier_in_tx: field, recipient: struct) */
    process_log: ((log_plaintext: { storage: FieldLike[], len: (bigint | number) }, tx_hash: FieldLike, unique_note_hashes_in_tx: { storage: FieldLike[], len: (bigint | number) }, first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_decimals() */
    public_get_decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_name() */
    public_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_symbol() */
    public_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_shield_gateway_beacon(beacon: struct) */
    set_shield_gateway_beacon: ((beacon: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** setup_refund(fee_payer: struct, user: struct, funded_amount: field, nonce: field) */
    setup_refund: ((fee_payer: AztecAddressLike, user: AztecAddressLike, funded_amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** shield(from: struct, amount: field, nonce: field) */
    shield: ((from: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** shielded_supply() */
    shielded_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** total_supply() */
    total_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_private(from: struct, to: struct, amount: field, nonce: field) */
    transfer_private_to_private: ((from: AztecAddressLike, to: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_public(from: struct, to: struct, amount: field, nonce: field) */
    transfer_private_to_public: ((from: AztecAddressLike, to: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_private(from: struct, to: struct, amount: field, nonce: field) */
    transfer_public_to_private: ((from: AztecAddressLike, to: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_public(from: struct, to: struct, amount: field, nonce: field) */
    transfer_public_to_public: ((from: AztecAddressLike, to: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unshield(from: struct, amount: field, nonce: field) */
    unshield: ((from: AztecAddressLike, amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Unshield: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, Transfer: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, Shield: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, Mint: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, Burn: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Unshield: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Token::Unshield"
},
        eventSelector: EventSelector.fromString("0xb13c00a1"),
        fieldNames: ["from","amount"],
      },
Transfer: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Token::Transfer"
},
        eventSelector: EventSelector.fromString("0xf4d27d12"),
        fieldNames: ["from","to","amount"],
      },
Shield: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Token::Shield"
},
        eventSelector: EventSelector.fromString("0xcb32feb0"),
        fieldNames: ["from","amount"],
      },
Mint: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Token::Mint"
},
        eventSelector: EventSelector.fromString("0x5d1bcd05"),
        fieldNames: ["to","amount"],
      },
Burn: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "authwit::aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "Token::Burn"
},
        eventSelector: EventSelector.fromString("0x479b1b70"),
        fieldNames: ["from","amount"],
      }
    };
  }
  
}
