[package]
name = "token"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/aztec-nr/aztec" }
compressed_string = {git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/aztec-nr/compressed-string" }
authwit={ git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/aztec-nr/authwit" }
uint_note={ git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/aztec-nr/uint-note" }
shield_gateway={ path="../shield_gateway" }
test_common={ path="../../lib/test_common" }
