[package]
name = "token"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.74.0", directory="noir-projects/aztec-nr/aztec" }
compressed_string = {git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.74.0", directory="noir-projects/aztec-nr/compressed-string"}
authwit={ git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.74.0", directory="noir-projects/aztec-nr/authwit"}
uint253 = { git = "https://github.com/ClarifiedLabs/aztec-uint253/", tag = "aztec-packages-v0.74.0" }
beacon={ path="../beacon" }
test_common={ path="../../lib/test_common" }
