[package]
name = "shield_gateway_storage"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.76.4", directory="noir-projects/aztec-nr/aztec" }
authwit={ git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.76.4", directory="noir-projects/aztec-nr/authwit"}
uint253 = { git = "https://github.com/ClarifiedLabs/aztec-uint253/", tag = "aztec-packages-v0.76.4" }
test_common = { path="../../lib/test_common" }
