[package]
name = "dev_advance_block"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.76.4", directory="noir-projects/aztec-nr/aztec" }
