services:
  ethereum:
    image: ghcr.io/clarifiedlabs/foundry:stable
    entrypoint: anvil -p 8545 --host 0.0.0.0 --chain-id 31337 --silent
    ports:
      - "8545:8545"
  aztec:
    image: aztecprotocol/aztec:0.82.2
    ports:
      - "8080:8080"
    environment:
      FORCE_COLOR: 0
      LOG_LEVEL: info
      ETHEREUM_HOSTS: http://ethereum:8545
      PXE_PORT: 8080
      PORT: 8080
      L1_CHAIN_ID: 31337
      DEPLOY_AZTEC_CONTRACTS_SALT: 1
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
      P2P_BLOCK_CHECK_INTERVAL_MS: 500
      SEQ_TX_POLLING_INTERVAL_MS: 500
      WS_BLOCK_CHECK_INTERVAL_MS: 500
      ARCHIVER_POLLING_INTERVAL_MS: 500
      TEST_ACCOUNTS: "true"
      VERSION: latest
    depends_on:
      - ethereum
    command: node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --sandbox
  bot:
    image: aztecprotocol/aztec:0.82.2
    environment:
      LOG_LEVEL: info
      ETHEREUM_HOSTS: http://ethereum:8545
      AZTEC_NODE_URL: http://aztec:8080
      BOT_NO_START: "false"
      BOT_MAX_PENDING_TXS: 10
      BOT_TX_INTERVAL_SECONDS: 10
      BOT_L1_PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      PXE_PROVER_ENABLED: "false"
      PROVER_REAL_PROOFS: "false"
      PORT: 8077
      PXE_PORT: 8077
    command: bash -c "sleep 30; node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --bot --pxe"
    depends_on:
      - ethereum
      - aztec
