[package]
name = "shield_gateway"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0-alpha-testnet.11", directory="noir-projects/aztec-nr/aztec" }
uint_note={ git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0-alpha-testnet.11", directory="noir-projects/aztec-nr/uint-note" }
test_common={ path="../../lib/test_common" }
