[package]
name = "portal"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0-alpha-testnet.11", directory="noir-projects/aztec-nr/aztec" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0-alpha-testnet.11", directory="noir-projects/aztec-nr/compressed-string" }
authwit={ git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0-alpha-testnet.11", directory="noir-projects/aztec-nr/authwit" }
token={ path="../token" }
