[package]
name = "portal"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.3", directory="noir-projects/aztec-nr/aztec" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.3", directory="noir-projects/aztec-nr/compressed-string" }
token={ path="../token" }
