name: Docker Build (API)

on:
  workflow_call: # Allow this workflow to be called by others
    inputs:
      push_images:
        description: Push built images to GHCR
        required: false
        type: boolean
        default: false
  workflow_dispatch: # Allow manual trigger
    inputs:
      push_images:
        description: Push built images to GHCR
        required: false
        default: 'false'

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    env:
      REGISTRY: ghcr.io
      ORG: turnstileportal
      PUSH_IMAGES: ${{ fromJSON(format('{0}', inputs.push_images)) && 'true' || 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Get Version
        id: versions
        run: |
          echo "version=v$(jq -r '.version' packages/api-common/package.json)" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        if: env.PUSH_IMAGES == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push migrations image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/common/Dockerfile
          push: ${{ env.PUSH_IMAGES == 'true' }}
          build-args: |
            SERVICE=@turnstile-portal/api-common
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORG }}/migrations:latest
            ${{ env.REGISTRY }}/${{ env.ORG }}/migrations:${{ steps.versions.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push collector image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/common/Dockerfile
          push: ${{ env.PUSH_IMAGES == 'true' }}
          build-args: |
            SERVICE=@turnstile-portal/collector
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORG }}/collector:latest
            ${{ env.REGISTRY }}/${{ env.ORG }}/collector:${{ steps.versions.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push api-service image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/common/Dockerfile
          push: ${{ env.PUSH_IMAGES == 'true' }}
          build-args: |
            SERVICE=@turnstile-portal/api-service
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORG }}/api-service:latest
            ${{ env.REGISTRY }}/${{ env.ORG }}/api-service:${{ steps.versions.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push api-init-contracts image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/common/Dockerfile
          push: ${{ env.PUSH_IMAGES == 'true' }}
          build-args: |
            SERVICE=@turnstile-portal/api-init-contracts
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORG }}/api-init-contracts:latest
            ${{ env.REGISTRY }}/${{ env.ORG }}/api-init-contracts:${{ steps.versions.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push turnstile-sandbox-deployer image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/common/Dockerfile
          push: ${{ env.PUSH_IMAGES == 'true' }}
          build-args: |
            SERVICE=@turnstile-portal/deployer
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORG }}/turnstile-sandbox-deployer:latest
            ${{ env.REGISTRY }}/${{ env.ORG }}/turnstile-sandbox-deployer:${{ steps.versions.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
