name: L1 Contract Tests

on:
  push:
    paths:
      - '/l1/**'
  pull_request:
    paths:
      - '/l1/**'
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      # `forge fmt` is disabled because it doesn't support `transient` yet
      # - name: Run Forge fmt
      #   working-directory: ./l1
      #   run: |
      #     forge fmt --check
      #   id: fmt

      - name: Run Forge build
        working-directory: ./l1
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: ./l1
        run: |
          forge test -vvv
        id: test
